### ISSUE TITLE
Error in three phase method example file

### ISSUE THREAD

**Issue by Mahamiho** [ladybug-tools/honeybee-grasshopper#11] opened 2017-09-06 15:27 UTC
Hey,
This is probably a very specific case, but I tried to set the toggle to true in the write field in the run radiance, and it gave me an error. It was in Swedish but if it is translated it as ''Can not translate exchange at index 0 from the specified character table to unicode ' . Can you tell me what is the problem? I could not install the new honeybee from the grasshopper installation file, so I dragged and dropped the components. I could see though that the folders needed in the C folder are there.

![image](https://user-images.githubusercontent.com/26859104/30120075-226a88aa-9328-11e7-9fbf-935ffb07a1b7.png)

Thanks for the help in advance,

**Comment by mostaphaRoudsari** [comment] 2017-09-07 00:03
@Mahamiho the error looks like you're having a special character in the name of a material or something like that. Can you share the folder with me?

**Comment by Mahamiho** [comment] 2017-09-08 14:44
Hey @mostaphaRoudsari,
you are right, it was a probelm in the directory path that it had a special character,I moved everything to the desktop instead. so now radiance seems to run, but no results are generated, I went through the folders but I am not sure whats the problem. Otherwise it could be a problem with my antivirus. Thanks for your help.

[1.zip](https://github.com/ladybug-tools/honeybee-grasshopper/files/1288199/1.zip)

**Comment by Mahamiho** [comment] 2017-09-08 14:45
thats the error now,
![error in running](https://user-images.githubusercontent.com/26859104/30216973-0c0cfe74-94b5-11e7-9f0e-37075aa60d40.PNG)

**Comment by Mahamiho** [comment] 2017-09-12 15:28
Hey,
I reran the file on another computer and now it is working fine. I guess it was the same problem that was posted by (inkmug)
you can close this post.
thanks,

**Comment by mostaphaRoudsari** [comment] 2017-09-12 16:08
Hi @Mahamiho, Thank you for the update. I'm going to close the issue as you said. You can also close it yourself if the issue is addressed!

**Closed as completed by mostaphaRoudsari** 2017-09-12 16:08 UTC
Labels: honeybee-core
